version: "3.8"

services:
  backend:
    image: ihebkhalfallah777/backend
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SERVER_PORT=8086
      - SERVER_SERVLET_CONTEXT_PATH=/Foyer

    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8086:8086"
    networks:
      - app-network
    # restart: always
  frontend:
    image: ihebkhalfallah777/front:latest
    container_name: frontend
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3001
      - NEXT_PUBLIC_UNIVERSITE_API_URL=http://backend:8086/Foyer/universite/addOrUpdate
      - NEXT_PUBLIC_UNIVERSITE_FINDALL_API_URL=http://backend:8086/Foyer/universite/findAll
      - NEXT_PUBLIC_STUDENT_API_URL=http://backend:8086/Foyer/student/addOrUpdate
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8086/Foyer
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: foyer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
