version: '3.8'

services:

  backend:
    image: groupe5-arctic01-2425:latest
    container_name: "foyer-backend-${BUILD_ID}"
    ports:
      - "8086:8086"
    environment:
      # Connexion à MySQL local (attention sous Linux, adapte host.docker.internal)
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass

      SERVER_PORT: 8086
      SERVER_SERVLET_CONTEXT_PATH: /Foyer

      # URLs des services existants
      SONARQUBE_URL: http://host.docker.internal:9000
      NEXUS_URL: http://host.docker.internal:8081
      PROMETHEUS_URL: http://host.docker.internal:9090
      GRAFANA_URL: http://host.docker.internal:3000

    restart: always
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
